### ISSUE TITLE
corrupt filesystem after flashing

### ISSUE THREAD

**Issue by christianwicke** [toremick/shorai-esp32#18]
Hello toremick,

I can flash the firmware without error, but when I try to connect with thonny the filesystem seem to be corrupt:
```
The filesystem appears to be corrupted. If you had important data there, you
may want to make a flash snapshot to try to recover it. Otherwise, perform
factory reprogramming of MicroPython firmware (completely erase flash, followed
by firmware programming).


Device is busy or does not respond. Your options:

  - wait until it completes current work;
  - use Ctrl+C to interrupt current work;
  - reset the device and try again;
  - check connection properties;
  - make sure the device has suitable MicroPython / CircuitPython / firmware;
  - make sure the device is not in bootloader mode.

The filesystem appears to be corrupted. If you had important data there, you
may want to make a flash snapshot to try to recover it. Otherwise, perform
factory reprogramming of MicroPython firmware (completely erase flash, followed
by firmware programming).

The filesystem appears to be corrupted. If you had important data there, you
may want to make a flash snapshot to try to recover it. Otherwise, perform
factory reprogramming of MicroPython firmware (completely erase flash, followed
by firmware programming).

(keeps on repeating)
```

I can press Ctrl-C and enter the REPL. But installation fails because of the corrupt filesystem:

```
The filesystem appears to be corrupted. If you had important data there, you
may want to make a flash snapshot to try to recover it. Otherwise, perform
factory reprogramming of MicroPython firmware (completely erase flash, followed
by firmware programming).

Traceback (most recent call last):
  File "_boot.py", line 11, in <module>
  File "inisetup.py", line 34, in setup
  File "inisetup.py", line 15, in check_bootsec
  File "inisetup.py", line 30, in fs_corrupted
KeyboardInterrupt: 
MicroPython v1.16-39-g4ada56d4c on 2021-07-01; ESP32 module with ESP32

Type "help()" for more information.

>>> import installation
>>> installation.install_now('xxx', 'xxxx')
connecting to network...
network config: ('192.168.178.160', '255.255.255.0', '192.168.178.1', '192.168.178.1')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "installation.py", line 5, in install_now
  File "TMInstaller.py", line 68, in download_and_install_update_if_available
OSError: [Errno 19] ENODEV
>>> 
```

However, I can flash MicroPython using thonny if I follow these instructions: https://randomnerdtutorials.com/getting-started-thonny-micropython-python-ide-esp32-esp8266/ . Then the filesystem is not corrupt.
I use this esp32: https://de.aliexpress.com/item/1005001838731651.html

Do you have any clue, what is going wrong?

Could you provide the installation module? Then I would try to install it over a bare MicroPython firmware.

Thanks a lot for your help and for sharing your project on github!

**Comment by christianwicke** [comment]
I found a workaround:
* After flashing MicroPython v1.23.0 I copied the main folder and the config.py to / on the esp32
* I also copied the main_example.py to boot.py on the esp32
* Small modifications to the code were necessary to get it running with MicroPython v1.23.0 (module ussl is now ssl).
* I documented this at https://github.com/christianwicke/shorai-esp32. The modified code is also there.

Afterwards I managed to control my Seiya air conditioner over mqtt.
